drivendataorg/zamba

appveyor.yml
Since the last commit (ba303ce), there have been changes to appveyor, conda, or some combination of the two that causes our build to fail with the error
```
TypeError: LoadLibrary() argument 1 must be str, not None
```
I found some discussion of the error here, https://github.com/conda/conda/issues/8836 . It doesn't give a clear answer though.
I was able to find a fix here:
https://github.com/TUW-GEO/pytesmo/pull/164/files#diff-180360612c6b8c4ed830919bbb4dd459
Although geopandas might have another solution here:
https://github.com/geopandas/geopandas/blob/master/appveyor.yml
Full disclosure: I have no idea how this fix works or how appveyor works. But I will say that this change makes the red x turn into a green dot.
=> Fix Appveyor CI failures

.github/pull_request_template.md, .gitignore, Dockerfile, docs/conf.py, docs/requirements.txt, requirements-dev.txt, requirements.txt, setup.py, zamba/__init__.py, zamba/config.py, zamba/convert_videos.py, zamba/models/blanknonblank.py, zamba/models/cnnensemble/requirements.txt, zamba/models/cnnensemble/src/config.py, zamba/models/cnnensemble/src/utils.py, zamba/models/cnnensemble_model.py, zamba/models/manager.py, zamba/models/mega_detector.py, zamba/models/model.py, zamba/tests/test_blanknonblank.py, zamba/tests/test_cnnensemble.py, zamba/tests/test_convert_videos.py, zamba/tests/test_mega_detector.py, zamba/utils.py, zamba/visualization.py
Incorporate the changes from [zamba-background-detection](https://github.com/drivendataorg/zamba-background-detection) into the main zamba package.
Major changes:
- `zamba/convert_videos.py`: resample videos prior to processing
- `zamba/models/mega_detector.py`: Mega object recognition that draws bounding boxes around objects in frames of a movie. Also includes code to extract features from this: number of key frames, number of detections, bounding box area
- `zamba/models/blanknonblank.py`: The winning model from prototyping -- use the "zamba" features combined with those derived from the Mega object recognition algorithm.
- `zamba/models/cnnensemble_model.py`: Incorporates the new blank/non-blank model to populate the "blank" probability for each video
Minor changes:
- Instead of …
=> Object recognition

.github/workflows/tests.yml, Makefile, requirements.txt, setup.py, zamba/cli.py, zamba/models/cnnensemble/src/single_frame_cnn.py, zamba/models/cnnensemble_model.py, zamba/tests/test_cli.py
Added a few parameters that significantly reduce the computation that we do by default. 
- Adds a `--resample` flag to indicate if we should re-encode the videos to a consistent size and frame rate (default `False`).
- Adds a `--separate_blank` flag to skip the additional blank/non-blank model that does object detection so is computationally intensive (default `False`)
We also used to try to pre-load a few frames from a video to see if it was valid. Turns out that videos can still fail to load downstream even if we are able to load the first frames. Now we catch invalid videos deeper in the algorithm code and then bookkeep those all the way back up to each ensemble member.
=> Optional resampling and blank/non-blank; updated error handling

zamba/models/cnnensemble_model.py
Fix failing local tests by checking that file paths exist for `valid_videos`. For resampling, we generate the output paths first but if a file can't be resampled, the path will exist in name only (no file). 
*Due to the long run times and large memory requirements, some tests cannot be completed on our CI platform. Those tests should be marked with `@pytest.skipif(zamba.config.codeship)` decorator. Run the tests locally using `pytest zamba` and paste the output below.*
```
13:33 $ make test
python -m pytest -s zamba
======================================== test session starts ========================================
platform linux -- Python 3.6.13, pytest-5.4.3, py-1.10.0, pluggy-0.13.1
rootdir: /home/emily/zamba
plugins: cov-2.10.0, mock-3.1.1
collected 13 items …
```
=> Check if file exists for valid videos

zamba/models/mega_detector.py
Updates default megadetector version to 4.1 instead of v3.
```
(zamba) ubuntu@ip-172-31-9-197:~/zamba$ make test
python -m pytest -s zamba
============================================================================================================================================================== test session starts ===============================================================================================================================================================
platform linux -- Python 3.6.13, pytest-5.4.3, py-1.10.0, pluggy-0.13.1
rootdir: /home/ubuntu/zamba
plugins: cov-2.10.0, mock-3.1.1
collected 13 items …
```
=> Update megadetector to version 4.1

tests/assets/sample_train_config.yaml, zamba/models/model_manager.py
Species is still OHE at the point where we add the extra columns. Fixed this and added `predict_all_zamba_species` to the test yaml so this gets tested.
=> Species bug fix

zamba/models/config.py
Assortment of fixes:
- need skip_on_failure on all root validators in order to get helpful validation error and not move to the next validator which will  give us a cryptic "values[...]" is None
- actually drop duplicate filepaths so we only get one row our per prediction. currently we just say we do this but it's not implemented
- model_name has a default so if you just pass a checkpoint, model_name will be specified. we don't need to remind users of this all the time and can just tell them we're using the checkpoint
=> Skip on failure, actually drop duplicates, clarify logging

tests/conftest.py, tests/test_model_manager.py, zamba/pytorch_lightning/utils.py
Top K accuracy fails to calculate if the number of classes is 2 or fewer. In that case, we just calculate accuracy instead.
=> Support training models with just two classes

docs/docs/configurations.md, docs/docs/index.md, docs/docs/models.md
Time distributed provides 32 labels not 31. This PR just changes 31 -> 32 in the docs plus some unavoidable space removing thanks to vscode.
=> 32 not 31 species

zamba/models/config.py, zamba/pytorch/dataloaders.py
If you're finetuning and having splits autogenerated, you're going to want to know which files were used for training vs. holdout, particularly so you can run your trained model on the holdout/test set. 
Changes:
- writes out filepath and split column to csv in save_dir / splits.csv
- incorporates fix for videos that cannot be loaded (warn and write all zeros)
Before merge:
=> Write out splits + fix for videos that cannot be loaded

Makefile
Closes #165 
Simple fix for the missing build requirement.
=> Add torch to build requirements in make requirements recipe

tests/assets/labels.csv, tests/conftest.py, tests/test_config.py, tests/test_model_manager.py, zamba/models/config.py, zamba/models/model_manager.py
This PR fixes the issue that caused the following error:
```
RuntimeError: Early stopping conditioned on metric val_macro_f1 which is not available. Pass in or modify your EarlyStopping callback to use any of the following: train_loss
```
The issue has to do with the `split` column. When we don't provide it in the labels, we use a random split. But we don't guarantee that we have all of the values from the split_proportions dict (e.g. `train` and `val` ) in the split column. With a small number of videos and the default proportions, all videos getting assigned to train (see in `splits.csv`). Since there are no val videos, there is no `val_f1_score`.
I considered implementing this without the random draw and instead calculating the number of samples that need to go into each split based on …
=> Ensure videos are allocated into all specified splits

docs/docs/models/species-detection.md
Remove unidentified from list of species in Python package docs. TBD how this will surface in the latest docs vs. the stable docs.
=> Remove unidentified from list of european species

.github/workflows/tests.yml, HISTORY.md, MANIFEST.in, setup.cfg
Videos weren't loading in latest version, and we were seeing a lot of these errors:
```
2021-12-17 01:11:44.274 | WARNING  | zamba.pytorch.dataloaders:__getitem__:118 - Video /data/blank3.mp4 could not be loaded. Using an array of all zeros instead.
```
Upon debugging, discovered this was because of the following stack trace:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.8/dist-packages/zamba/data/video.py", line 468, in load_video_frames
mdlite = MegadetectorLiteYoloX(config=config.megadetector_lite_config)
File "/usr/local/lib/python3.8/dist-packages/zamba/object_detection/yolox/megadetector_lite_yolox.py", line 88, in __init__
checkpoint = torch.load(path, map_location=config.device)
File …
```
=> Update path to pretrained yolox asset

setup.cfg, tests/test_megadetector_lite_yolox.py
`Pillow` is used by a number of our packages, including `detectron2-densepose`, `fvcore`, `pytorchvideo`, and `torchvision`.
The new release of pillow 9.0.0 (https://pypi.org/project/Pillow/#history) causes the `detect_image` test to fail ([example](https://github.com/drivendataorg/zamba/runs/4706439540?check_suite_focus=true)) as the outputted bounding boxes are slightly shifted. I've reproduced this issue locally and can confirm that pillow 8.4.0 yields `[0.09714001, 0.04298288, 0.9931407, 1.0082585]` whereas 9.0.0 yields `[0.09690314, 0.04301501, 0.9931333 , 1.0082883]`. 
This PR updates that test accordingly.
=> Update expected bounding box in test based on new pillow version

HISTORY.md, Makefile, docs/docs/changelog.md, docs/docs/changelog/index.md, docs/docs/index.md, docs/mkdocs.yml
This little PR makes "changelog" a clickable header in the docs table of content to mimic the behavior of other sections with only one page (e.g. contribute to zamba).
Bonus fix:
- remove extra line breaks in the history markdown file
=> Make changelog a clickable header in the docs index

Makefile, docs/docs/contribute/index.md, docs/docs/install.md, requirements-dev.txt, setup.cfg, tests/test_cli.py, tests/test_densepose.py, tests/test_load_video_frames.py, tests/test_model_manager.py
`requirements-dev.txt` no longer installs the densepose extra since DensePose requires torch to be installed first. The appropriate install and test commands for DensePose contributions are now laid out on the contributing page.
Bonus fixes
- update installation instructions to use v4 as brew will now install v5 by default
- skip densepose tests by default so that `make tests` runs with the default dev install. the verbose pytest will show that these tests are skipped
=> Separate out densepose install for contributing instructions

.github/workflows/tests.yml
Set the ffmpeg version in the github action workflow since zamba is only supported with ffmpeg v4.
Closes #184
=> Pin version for ffmpeg

tests/test_config.py, zamba/models/config.py
For the labels csv, we required "filepath" and "label" and support optional columns "split" and/or "site." If a labels csv contains extra columns, we should exclude those as these can lead to unintended consequences.
For example, if there is a column with "species_" prefix, e.g. "species_VE", this column will get included in the species list (which results from label -> species -> get dummies -> filter columns with "species_"). By explicitly excluding extra columns, we avoid this bug.
Similarly for predict, we should exclude any columns that are not "filepath" as this interferes with indexing in the dataloader.
=> Exclude extra columns in labels df (TrainConfig) and filepaths df (PredictConfig)

tests/test_densepose.py, tests/test_model_manager.py, zamba/models/config.py, zamba/models/model_manager.py, zamba/models/utils.py
Main changes:
- downloads public checkpoint file to top level model_cache_dir (this supports look ups in the correct place on future runs)
- if cached checkpoint file exists (and no other checkpoint was passed in), put the cached path on the `checkpoint` property in TrainConfig
These changes allow the previously downloaded file to actually get used on future runs. Previously, we were seeing "downloading model weights" on every run.
Closes #189
=> Fix caching

setup.cfg
With the latest thop version released on June 10, 2022, `thop` requires onnx but doesn't install it. Our options are either to use an earlier version of thop or add the onnx dependency ourselves. Given that we don't need to use onnx, I've implemented the former.
The current error is as follows:
```
zamba --help
---> Running in f3d991f7f04a
Traceback (most recent call last):
File "/usr/local/bin/zamba", line 5, in <module>
from zamba.cli import app
File "/usr/local/lib/python3.8/dist-packages/zamba/cli.py", line 10, in <module>
from zamba.data.video import VideoLoaderConfig
File "/usr/local/lib/python3.8/dist-packages/zamba/data/video.py", line 22, in <module>
from zamba.object_detection.yolox.megadetector_lite_yolox import (
File …
```
=> Pin thop to avoid onnx dependency

HISTORY.md, docs/docs/changelog/index.md, setup.cfg, zamba/models/utils.py
Fix parenthesis so `destination_dir` is a `PosixPath`
Bonus fix:
- removes ceiling for `protobuf` since this is handled by the latest tensorboard release
=> Fix bug in download_weights

docs/docs/debugging.md
The accepted loguru log levels are all caps. This PR fixes the documentation example so it runs correctly.
=> Capitalize log level

Makefile, pyproject.toml
=> Holding back setuptools

tests/test_npy_cache.py, zamba/data/video.py
Factoring out `get_cached_array_path`, avoiding the pop `bug`, and adding tests.
Closes #201
=> 201 Factor out `get_cached_array_path`

MANIFEST.in
Fix issue where `hparams.yaml` isn't included in the MANIFEST. Instead, let's just include all the files in the official models directory.
Without this, we get the following error (if not using an editable install)
```
FileNotFoundError: [Errno 2] No such file or directory: '.../python3.9/site-packages/zamba/models/official_models/time_distributed/hparams.yaml'
```
=> Include hparams in MANIFEST

zamba/models/config.py
Current `data_dir` gets resolved to an absolute path, which causes caching to fail.
The fix is to leave it alone -- nothing wrong with relative paths.
Closes #218
=> Don't resolve filepaths

setup.cfg, zamba/models/config.py
Closes #216 
Checking for missing files is slow with goofys. It seems to make lots of small queries to the file system. Running them in parallel with `pqdm` is much faster. The speed depends on the state of the file system cache, but we can check 246,000 files in 5-8 minutes, compared to about two hours the slow way.
Using `pqdm` with threads is faster than with processes. Using 16 threads seems to be fast and robust. With more threads, things go faster, but you start to see unpredictable I/O errors.
If an error occurs, it falls back to the slow way.
This fix has only been tested with video files that are mounted from S3 using goofys. It might be good to test with videos stored in a local file system, too.
=> Checking for missing files in parallel

docs/docs/configurations.md, docs/docs/train-tutorial.md, tests/assets/sample_train_config.yaml, tests/conftest.py, tests/test_config.py, tests/test_instantiate_model.py, zamba/models/config.py, zamba/models/model_manager.py, zamba/models/publish_models.py, zamba/models/utils.py
Refactors the logic in `instantiate_model` to branch on `is_subset` to be more explicit. The previous logic tried to group the cases for replacing the head vs. resuming training. 
```
elif not predict_all_zamba_species or not is_subset:
...
elif is_subset:
...
```
This new code change should not change the behavior, but should be more readable. The branching structure is now:
```
if is_subset:
if predict_all_zamba_species:
resume_training()
else:
replace_head()
else:
replace_head()
```
This also allows us to enforce that `is_subset` (based on the model species and the labels species) is in agreement with `predict_all_zamba_species`. Notes:
- `predict_all_zamba_species` is True by default. We assume that if you're finetuning on a subset of data, you still want all the zamba species. If you …
=> Refactor branching structure for finetuning vs. resuming training

tests/test_config.py, tests/test_instantiate_model.py, zamba/models/config.py, zamba/models/model_manager.py, zamba/models/utils.py
Fixes #234 
#229 introduced a bug whereby the new columns added to the labels file were in a different order than what is on the model. This PR fixes that by setting up the correct one hot encoded labels in the `preprocess_labels` validator rather than `instantiate_model`. Using the `use_default_model_labels`, we know whether the labels file should contain columns (with all zeroes) for species that are not present in the labels but are on the base model. Using a pd.Categorical before `get_dummies` allows us to generate these columns.
Running `zamba train --config tests/assets/sample_train_config.yaml` now works; the labels file has three species present in zamba but trains a model that outputs the full set of 32 labels.
=> Set up correct OHE labels for subsets that use default model labels

zamba/cli.py
Fixes #233 
Relevant part of typer docs explaining exception and error handling: https://typer.tiangolo.com/tutorial/exceptions/
We can turn off the `rich` behavior entirely, but I propose just turning off the "show local variables" behavior. This way, we still get a more nicely colored stack trace, but with the same amount of info as before. 
Below is a screenshot from the example case, showing the new behavior:
=> Don't show local variables in exceptions and errors

docs/docs/models/species-detection.md
Previously the docs said that the model outputs `blank` and `nonblank`, but since it is a binary model, it only outputs `blank` (nonblank is 1 minus blank). This PR updates the docs to reflect this.
=> Clarify BNB only outputs `blank`

zamba/models/model_manager.py, zamba/pytorch_lightning/utils.py
`DDPPlugin` was deprecated in pytorch lightning [1.8](https://github.com/Lightning-AI/lightning/releases) which came out today. Replace with supported `DDPStrategy`. We don't pin PTL, so we are subject to deprecated code in new releases.
Bonus fix:
- address checkpoint warning
```
2022-11-01 19:42:05.757 | INFO     | zamba.models.model_manager:train_model:331 - Calculating metrics on validation set.
/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py:129: UserWarning: `.validate(ckpt_path=None)` was called without a model. The best model of the previous `fit` call will be used. You can pass `.validate(ckpt_path='best')` to use the best model or `.validate(ckpt_path='last')` to use the last model. If you pass a value, this warning will be …
```
=> Change DDPPlugin to DDPStrategy

tests/test_load_video_frames.py, zamba/data/video.py
If `VIDEO_CACHE_DIR` gets set to an empty string or 0, it will be interpreted as True for caching. This PR adds logic so that empty strings or 0s in the environment variable will be interpreted as no caching is desired.
=> Interpret empty `VIDEO_CACHE_DIR` as None

.github/workflows/tests.yml, README.md, docs/docs/api-reference/depth_config.md, docs/docs/api-reference/depth_manager.md, docs/docs/index.md, docs/docs/models/depth.md, docs/docs/models/species-detection.md, docs/mkdocs.yml, setup.cfg, tests/test_cli.py, tests/test_depth.py, zamba/cli.py, zamba/models/config.py, zamba/models/densepose/config.py, zamba/models/depth_estimation/__init__.py, zamba/models/depth_estimation/config.py, zamba/models/depth_estimation/depth_manager.py, zamba/models/publish_models.py, zamba/pytorch/transforms.py
This implementation takes in a folder of videos (or csv with video filepaths) and outputs a csv of distance estimates for each frame (and detection). 
For frames with no detection, distance is null. If there are multiple detections in that frame, there is one line per detection. For example
```
filepath,time,distance
tests/assets/videos/data/raw/goualougo_2013/gorillas_2013/MPI_FID_20_Duboscia/14-Jun-2013/FID_20_Duboscia_2013-6-14_0083.AVI,0,7.4
tests/assets/videos/data/raw/goualougo_2013/gorillas_2013/MPI_FID_20_Duboscia/14-Jun-2013/FID_20_Duboscia_2013-6-14_0083.AVI,0,7.4
tests/assets/videos/data/raw/goualougo_2013/gorillas_2013/MPI_FID_20_Duboscia/14-Jun-2013/FID_20_Duboscia_2013-6-14_0083.AVI,1,
tests/assets/videos/data/raw/goualougo_2013/gorillas_2013/MPI_FID_20_Duboscia/14-Jun-2013/F …
```
=> Add depth module

tests/test_cli.py, tests/test_load_video_frames.py, zamba/cli.py, zamba/models/config.py, zamba/models/depth_estimation/depth_manager.py, zamba/models/efficientnet_models.py, zamba/models/model_manager.py, zamba/pytorch_lightning/utils.py
Fixes #258 -- the latest black changed rules about whitespace lines
Fixes #256 -- PTL 1.9.0 introduces migrations applied to checkpoints saved with previous versions ([docs](https://pytorch-lightning.readthedocs.io/en/stable/common/checkpointing_migration.html)). The tests were erroring since they were looking for `global_step` and `pytorch-lightning_version`, which are attributes that weren't included in the dict written out by `to_disk`.
`to_disk` is only used in the test suite. I added a note to clarify that `to_disk` mimics the [`weights_only` option](https://github.com/Lightning-AI/lightning/blob/44c9e385acecc8696668da044c9b14a5152ee931/src/lightning/pytorch/trainer/connectors/checkpoint_connector.py#L427-L447) in saving out the checkpoint file.  Generally, saving to disk is done …
=> Support recent versions of black and lightning

.github/workflows/tests.yml, README.md, docs/docs/index.md, docs/docs/install.md, docs/docs/models/depth.md, pyproject.toml, zamba/models/model_manager.py, zamba/models/utils.py, zamba/pytorch_lightning/utils.py
Updates how we set the accelerator and devices based on recent PyTorch Lightning changes.
[`pl.Trainer`](https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.trainer.trainer.Trainer.html#lightning.pytorch.trainer.trainer.Trainer) now accepts `accelerator` ("cpu", "gpu", etc."), `strategy`, and `devices` params instead of `num_gpus`. This PR adds a utility to configure accelerator and devices based on the number of user-specified gpus. 
Pros:
- keeps the command line to the same limited set of options (e.g. just specifying number of gpus instead of exposing both the cpu/gpu option as well as number of devices/cores)
- allows us to validate user-provided input up front to ensure that training won't fail after the long video loading check
Cons
- doesn't allow the user to specify …
=> Updates for PyTorch Lightning 2.0 release

pyproject.toml, tests/test_config.py
In [pandas 2.0.0](https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html), the `.append` method got deprecated. The guidance is to use [`.concat`](https://pandas.pydata.org/docs/dev/reference/api/pandas.concat.html#pandas.concat) instead. This PR makes those updates. This only impacts our tests.
=> Use concat instead of append for pandas 2.0

tests/conftest.py, tests/test_instantiate_model.py, zamba/models/efficientnet_models.py, zamba/models/model_manager.py, zamba/models/slowfast_models.py, zamba/pytorch_lightning/utils.py
=> Specify map location when loading model

.github/workflows/docs-latest.yml, .github/workflows/docs-preview.yml, .github/workflows/release.yml, .github/workflows/tests.yml
Adds the `maximize-build-space` action:
https://github.com/easimon/maximize-build-space
This removes extra software on the runner and re-allocates space to the runners working directory.
`root-reserve-mb` - Saves space on the root of the file system rather than allocating it all to the local running directory (e.g., anything saved to temp dirs). Needed to balance the pip installs and weight downloads, which go to temp dirs.
More software can be removed if necessary, it just makes each run take longer. See this table for which packages can be removed and how much space you get:
https://github.com/easimon/maximize-build-space/blob/test-report/README.md
=> Add maximize-build-space step

.github/workflows/tests.yml
Tests are failing because the test for installation runs out of space:
https://github.com/drivendataorg/zamba/actions/runs/6366532961
Closes #293 
Closes #292
=> More space for build and install step in CI

pyproject.toml, tests/test_densepose.py
Caused by:
densepose broken after torch==2.1.0; https://github.com/facebookresearch/detectron2/issues/5110
Closes #296
=> Fix failing densepose tests

docs/docs/install.md
Per #294, current instructions can be confusing.
- Remove Anaconda on Windows link
- Add list of packages used on zamba cloud for ubuntu support
- Add Docker/WSL links to windows section
Closes #294
=> Update windows documentation

requirements-dev/lint.txt, zamba/models/densepose/densepose_manager.py, zamba/models/model_manager.py, zamba/models/slowfast_models.py, zamba/pytorch/dataloaders.py, zamba/pytorch/transforms.py
Reformats with black 24.1.0 with 2024 stable style, and puts a floor on black 24.1.0 in dev requirements. 
Closes #307
=> Update for black 24.1.0

.github/workflows/docs-latest.yml, .github/workflows/docs-preview.yml, .github/workflows/release.yml, .github/workflows/tests.yml, pyproject.toml
Swaps in [drivendataorg/setup-python-uv-action](https://github.com/drivendataorg/setup-python-uv-action) and installs our dependencies with uv (without caching).
Closes #312
=> Use uv for CI

.github/workflows/tests.yml
This takes advantage of the fact that `uv` now recursively allows URL requirements for local dependencies: https://github.com/astral-sh/uv/releases/tag/0.1.27
=> Use uv to install wheel and source dists

.github/workflows/tests.yml, pyproject.toml, tests/test_load_video_frames.py
Closes #315 
Closes #326 
Closes #327 
Closes #328
=> Fix ffmpeg install on macos

docs/docs/yaml-config.md
Fixes a small typo in the docs with instructions for importing the `ModelManager` class.
From:
```python
from zamba.models.manager import ModelManager
```
To:
```python
from zamba.models.model_manager import ModelManager
```
=> Fix ModelManager import in docs

.github/workflows/release.yml, .github/workflows/tests.yml
The [easimon/maximize-build-space](https://github.com/easimon/maximize-build-space/) action is a victim of GitHub changing stuff about how the runners are set up. A lot of the functionality is broken, and this affects us because `root-reserve-mb` doesn't work anymore. 
- https://github.com/easimon/maximize-build-space/issues/44
- https://github.com/easimon/maximize-build-space/issues/48
This PR replaces the action with some `sudo rm -rf` commands that just duplicate what the action was doing for the parts where it deletes unwanted software.
=> Replace maximize-build-space action

.github/workflows/docs-latest.yml, .github/workflows/docs-preview.yml, .github/workflows/release.yml, .github/workflows/tests.yml, Makefile, README.md, docs/docs/index.md, docs/docs/install.md, pyproject.toml, zamba/models/config.py
PR to update the python required version to be >= 3.10 -- this required unpinning the `thop` dependency as well as changing the `ModelEnum.time_distributed` extraction of the string to `ModelEnum.time_distributed.value`.
Closes #310 
Closes #192
=> Upgrade the required python version to python>=3.11

.github/failed_build_issue_template.md, .github/workflows/tests.yml
Switches the failed build notification issue action to jayqi/failed-build-issue-action, which will reuse an already open issue and be less noisy.
=> Switch to jayqi/failed-build-issue-action

HISTORY.md, docs/docs/changelog/index.md
Looks like `make docs` wasn't run here: https://github.com/drivendataorg/zamba/commit/d8677fb2d8cc34eb19b93ee774e3f9991bbeb5b0
=> Fix year in changelog and add missing file

.github/workflows/tests.yml
Applies the OS matrix to the cache population job. 
Closes #379 
Learnings: 
- There's a `enableCrossOsArchive` option but it seems like it's specifically for Ubuntu->Windows or macOS->Windows. Weird implementation.
- Ubuntu<->macOS will randomly break if either one has zstd updated in the runner image. [reference](https://github.com/actions/cache/issues/1110) Seems like this is what happened to us with #379?
=> Fix unreliable cross-OS caching for model weights
